<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDate($date)
    {
        $qb = $this
            ->createQueryBuilder('b')
            ->where('b.date = :date')
            ->setParameter('date', $date)
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
