<?php

namespace Louvre\BilletterieBundle\Repository;

use Louvre\BilletterieBundle\Entity\Commande;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * @return Commande
    */
    public function findCodeResa($coderesa)
     {
         $qb = $this
             ->createQueryBuilder('c')
             ->where('c.coderesa = :coderesa')
             ->setParameter('coderesa', $coderesa)
         ;
         return $qb
             ->getQuery()
             ->getOneOrNullResult()
             ;
     }
}
