<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTarif($age)
    {
        $qb = $this
            ->createQueryBuilder('t')
            ->where('t.age_mini <= :age')
            ->andWhere('(t.age_maxi > :age')
            ->setParameter('age', $age)
        ;
        dump($qb);
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
