<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * Type_billetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_billetRepository extends \Doctrine\ORM\EntityRepository
{
}
