louvre_billetterie_homepage:
    path:     /
    defaults: { _controller: LouvreBilletterieBundle:Orders:index }

louvre_billetterie_infos:
    path:     /infos
    defaults: { _controller: LouvreBilletterieBundle:Orders:infos }

louvre_billetterie_commande:
    path:     /commande
    defaults: { _controller: LouvreBilletterieBundle:Orders:commande }

louvre_billetterie_email:
    path:     /confirmation
    defaults: { _controller: LouvreBilletterieBundle:Orders:email }

louvre_billetterie_paiement:
    path:     /paiement
    defaults: { _controller: LouvreBilletterieBundle:Orders:paiement }

louvre_billetterie_videsession:
    path:     /videsession
    defaults: { _controller: LouvreBilletterieBundle:Orders:videsession }
