services:
#    louvre_billetterie.example:
#        class: Louvre\BilletterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    billetterie.tarif:
        class: Louvre\BilletterieBundle\Calcul\LouvreTarif