services:
#    louvre_billetterie.example:
#        class: Louvre\BilletterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    myrepository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Louvre\BilletterieBundle\Entity\Tarif


    billetterie.tarif:
        class: Louvre\BilletterieBundle\Calcul\LouvreTarif
        arguments:
            - "@myrepository"

    billetterie.email:
        class: Louvre\BilletterieBundle\Email\EnvoiMail
        arguments:
            - "@mailer"
            - "@twig"

    validator.unique.controle_date:
        class: Louvre\BilletterieBundle\Validator\ControleDateValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: controle_date }

    billetterie.stripe:
        class: Louvre\BilletterieBundle\Stripe\StripeService
        arguments:
            - "@mailer"
            - "@twig"

    commande_assembler:
        class: Louvre\BilletterieBundle\Assembler\CommandeAssembler
        arguments:
            - "@doctrine.orm.entity_manager"
            - Louvre\BilletterieBundle\Entity\Tarif
            - Louvre\BilletterieBundle\Entity\Type_billet