services:
#    louvre_billetterie.example:
#        class: Louvre\BilletterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    myrepository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Louvre\BilletterieBundle\Entity\Tarif


    billetterie.tarif:
        class: Louvre\BilletterieBundle\Calcul\LouvreTarif
        arguments:
            - "@myrepository"

    billetterie.email:
        class: Louvre\BilletterieBundle\Email\EnvoiMail
        arguments:
            - "@mailer"
            - "@twig"
            - "@knp_snappy.pdf"

    validator.unique.controle_date:
        class: Louvre\BilletterieBundle\Validator\ControleDateValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: controle_date }

    billetterie.stripe:
        class: Louvre\BilletterieBundle\Stripe\StripeService
        arguments:
            - "@mailer"
            - "@twig"

    repositorycommande:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Louvre\BilletterieBundle\Entity\Commande

    commande_assembler:
        class: Louvre\BilletterieBundle\Assembler\CommandeAssembler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@repositorycommande"

    #pdf_generator:
    #   class: "%pdf_generator_class%"
    #    arguments: ["@knp_snappy.pdf", "@twig"]


    #pdf_generator:
    #    class: "%pdf_generator_class%"
    #    arguments: ["@knp_snappy.pdf", "@twig"]
    #    options:
    #        - { name: 'viewport-size', value: ‘1024x768’ }
    #        - { name: 'page-size', value: 'A4' }